POST http://localhost:5000/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RzZWNvbmRAZ21haWwuY29tIiwiaWQiOjIsImlhdCI6MTcwMDQ5MTE3NH0.xQL_63QXw0lfMq13N4nzn_jsqY64NhuLHrOA4pwjgRU

{
    "title": "test title third one",
    "author": "nuuttinyyssonen",
    "url": "www.google.com23123",
    "likes": 0,
    "year": 2015
}