POST http://localhost:5000/api/logout
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im51dXR0aS5ueXlzc29uZW5AZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTcwMDUwMDE1NH0.pxvv_zYSnz4cbenNdq6FQ9qQss-M4tn-mxRtGtEDap8
