POST http://localhost:5000/api/blogs 
content-type: application/json

{
    "title": "This is just third test title",
    "author": "Third test person",
    "url": "www.google.com",
    "likes": 1300
}